/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.divesafe.application;

import java.sql.Date;

import ca.mcgill.ecse.divesafe.JavaFx.DiveSafeFxmlView;
import ca.mcgill.ecse.divesafe.model.DiveSafe;
import ca.mcgill.ecse.divesafe.persistence.DiveSafePersistence;
import javafx.application.Application;

public class DiveSafeApplication {

  public static final boolean DARK_MODE = true;

  private static DiveSafe diveSafe;

  public static void main(String[] args) {
    // Launch UI here (For Iteration 4)
    /**
     * @author JZ
     */
    Application.launch(DiveSafeFxmlView.class, args);
  }

  public static DiveSafe getDiveSafe() {
    if (diveSafe == null) {

      /**
       * @author Jiahao Zhao
       */

      diveSafe = DiveSafePersistence.load();
    }

    return diveSafe;
  }

  /**
   * This is the setter to create a new Dive Safe season in the application with
   * the required parameters.
   * 
   * @author Siger Ma
   * @param aStartDate          - Start date of the season
   * @param aNumDays            - Duration of the season
   * @param aPriceOfGuidePerDay - Price of a guide for the season
   */

  public static void setDiveSafe(Date aStartDate, int aNumDays, int aPriceOfGuidePerDay) {
    diveSafe = new DiveSafe(aStartDate, aNumDays, aPriceOfGuidePerDay);
  }
}
